name: Trigger Jenkins Pipeline

on:
  push:
    branches:
      - universite

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job
        env:
          JENKINS_USER: "admin"
          JENKINS_API_TOKEN: "11f65d0948b0b0f91c935ed9c655677855"
          JENKINS_URL: "http://192.168.1.100:8080/job/Mohamed_Rzem_5ArcTic7/build"

        run: |
          curl -X POST -u admin:11f65d0948b0b0f91c935ed9c655677855 https://192.168.1.100:8080/job/Mohamed_Rzem_5ArcTic7/build

